from typing import List, Optional
from enum import IntEnum

class Layout(IntEnum):
    Random = 0
    Circular = 1
    Spring = 2

class GraphStyle:
    node_color: str
    node_border: str
    node_radius: int
    marker_svg: str
    marker_fill: str
    marker_width: int
    marker_height: int
    line_color: str
    line_min_width: int
    line_max_width: int
    dynamic_line_size: bool

    def __init__(
        self,
        node_color: Optional[str] = None,
        node_border: Optional[str] = None,
        node_radius: Optional[int] = None,
        marker_svg: Optional[str] = None,
        marker_fill: Optional[str] = None,
        marker_width: Optional[int] = None,
        marker_height: Optional[int] = None,
        line_color: Optional[str] = None,
        line_min_width: Optional[int] = None,
        line_max_width: Optional[int] = None,
        dynamic_line_size: Optional[bool] = None,
    ) -> None: ...

class Graph:
    nodes: list[Node]
    def add_node(self, label: str) -> None: ...
    def create_connection(self, from_label: str, to_label: str, weight: float = 0., directed: bool = False) -> None: ...
    def get_connections(self) -> list: ...
    @staticmethod
    def from_adjacency_matrix(adj_matrix: list, directed: bool = False, custom_labels: list | None = None) -> "Graph": ...
    @staticmethod
    def from_net_file(file_path: str) -> "Graph": ...
    @staticmethod
    def from_json_file(adj_matrix: list) -> "Graph": ...
    def generate_adjacency_matrix(self) -> list: ...
    def get_total_weight(self) -> float: ...
    def get_mean_weight(self) -> float: ...
    def get_node_count(self) -> int: ...
    def get_edge_count(self) -> int: ...
    def get_density(self, directed: bool = False) -> float: ...
    def compute_degrees(self, node_label: str) -> dict: ...
    def get_all_nodes_degrees(self) -> dict: ...
    def get_average_degree(self, directed: bool = False) -> float: ...
    def get_centrality_degree(self, node_label: str) -> dict: ...
    def get_node_stregth(self, node_label: str) -> dict: ...
    def get_degree_distribution(self) -> dict: ...
    def compute_entropy(self) -> dict: ...
    def get_max_possible_entropy(self) -> float: ...
    def get_skewness(self) -> dict: ...
    def dfs(self, start_node_label: str) -> List[str]: ...
    def bfs(self, start_node_label: str) -> List[str]: ...
    def dijkstra(self, start_node_label: str) -> dict: ...
    def output_svg(self, layout: Layout = Layout.Random, override_positions: bool = False, style: Optional[GraphStyle] = None) -> str: ...
    def output_html(self, file_name: str, layout: Layout = Layout.Random, override_positions: bool = False, style: Optional[GraphStyle] = None) -> None: ...
    def output_net_file(self, file_name: str) -> None: ...
    def output_json_file(self, file_name: str) -> None: ...


class Node:
    label: str
    def add_connection(self, node: "Node", weight: float, directed: bool) -> None: ...
