use std::fs;
use std::io::{BufWriter, Error, Write};
use crate::{_Node};
use crate::layout::layout::{normalize_x, normalize_y};
use crate::file_reader_core::file_reader::{JsonConnection, JsonGraph, JsonNode};
use std::fs::File;


pub trait Writeable {
    fn write_file(&self, path: &str, content: &str) -> Result<(), Error>;
}

pub struct HtmlWriter {}

impl Writeable for HtmlWriter {
    fn write_file(&self, path: &str, content: &str) -> Result<(), Error> {
        let html_string = include_str!("../file_writer_core/template.html");
        let js_string = include_str!("../file_writer_core/script.js");

        let html_with_svg = html_string.replace("ESCAPE_SVG", content);
        let final_string = html_with_svg.replace("ESCAPE_SCRIPT", &js_string);

        fs::write(path, final_string)?;

        return Ok(());
    }
}


pub fn write_net_file(path: &str, nodes: Vec<_Node>, all_edges: &[(usize, usize, f32, bool)]) -> Result<(), Error>{
    let mut content_string: String = String::new();

    let mut edges: Vec<(usize,usize,f32)> = Vec::new();
    let mut arcs: Vec<(usize,usize,f32)> = Vec::new();

    content_string += "*Vertices\n";
    for node in &nodes {
        content_string += &format!("{} \"{}\"", node.index.unwrap_or(0), node.label);
        if !node.x.is_none() && !node.y.is_none() {
            content_string += &format!(" {} {}", normalize_x(node.x.unwrap()), normalize_y(node.y.unwrap()));
        }
        content_string += "\n";
    }

    for &(from_index, to_index, weight, directed) in all_edges {
        if directed {
            arcs.push((from_index, to_index, weight));
        } else {
            edges.push((from_index, to_index, weight));
        }
    }

    if !edges.is_empty() {
        content_string += "*Edges\n";
        for (from_index ,to_index, weight) in edges {
            content_string += &format!("{} {} {}\n", from_index, to_index, weight);
        }
    }

    if !arcs.is_empty() {
        content_string += "*Arcs\n";
        for (from_index ,to_index, weight) in arcs {
            content_string += &format!("{} {} {}\n", from_index, to_index, weight);
        }
    }

    fs::write(path, content_string)?;

    return Ok(());
}

pub fn write_json_file(path: &str, nodes: Vec<_Node>, all_edges: &[(usize, usize, f32, bool)]) -> Result<(), Error>{
    let mut json_nodes: Vec<JsonNode> = Vec::new();
    let mut json_edges: Vec<JsonConnection> = Vec::new();
    let mut json_arcs: Vec<JsonConnection> = Vec::new();

    for node in &nodes {
        let json_node = JsonNode {
            label: node.label.clone(),
            x: node.x,
            y: node.y
        };
        json_nodes.push(json_node);
    }

    for &(from_index, to_index, weight, directed) in all_edges {
        let json_conn = JsonConnection {
            source: nodes[from_index].label.clone(),
            target: nodes[to_index].label.clone(),
            weight: weight,
        };

        if directed {
            json_arcs.push(json_conn);
        } else {
            json_edges.push(json_conn);
        }
    }

    let json_graph = JsonGraph {
      nodes: json_nodes,
      edges: Some(json_edges),
      arcs: Some(json_arcs)
    };

    let file = File::create(path)?;
    let writer = BufWriter::new(file);

    serde_json::to_writer_pretty(writer, &json_graph)?;

    return Ok(());
}

pub fn write_mtx_file(path: &str, n_nodes: usize, n_edges: usize, all_edges: impl Iterator<Item=(usize, usize, f32, bool)>) -> Result<(), Error> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);

    writeln!(writer, "%%MatrixMarket matrix coordinate real general")?;
    writeln!(writer, "% Generated by netfog")?;
    writeln!(writer, "{} {} {}", n_nodes, n_nodes, n_edges)?;

    for (from_idx, to_idx, weight, _directed) in all_edges {
        writeln!(writer, "{} {} {}", from_idx + 1, to_idx + 1, weight)?;
    }

    return Ok(());
}

pub fn write_edge_list_file(path: &str, nodes: &[_Node], all_edges: impl Iterator<Item=(usize, usize, f32, bool)>) -> Result<(), Error> {
    let file = File::create(path)?;
    let mut writer = BufWriter::new(file);

    for (from_idx, to_idx, weight, _directed) in all_edges {
        let from_label = &nodes[from_idx].label;
        let to_label = &nodes[to_idx].label;
        writeln!(writer, "{} {} {}", from_label, to_label, weight)?;
    }

    return Ok(());
}
